package com.mybanksystem.util;

public enum MenuOption {
    CREATE_A_NEW_BANK,
    SEE_LIST_OF_BANKS,
    CREATE_A_NEW_ACCOUNT,
    MAKE_A_NEW_TRANSACTION,
    WITHDRAW,
    DEPOSIT,
    NORMAL,
    SEE_LIST_OF_ACCOUNTS,
    CHECK_ACCOUNT_DETAILS,
    CHECK_BANK_DETAILS,
    CHECK_TOTAL_TRANSACTION_FEE_AMOUNT,
    CHECK_TOTAL_BANK_TRANSFER_AMOUNT,
    BACK,
    EXIT,
    INVALID_OPTION
}
